// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdyX93UkyYlFmcs-JuQdgOyoMcF6G7Gw4',
    appId: '1:609475407163:web:7d5b63bb613fa52d9b1b1e',
    messagingSenderId: '609475407163',
    projectId: 'gen-lang-client-0495386713',
    authDomain: 'gen-lang-client-0495386713.firebaseapp.com',
    storageBucket: 'gen-lang-client-0495386713.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjJgmLPa3EUeEhpzqzHutWQiGMu0TsGWo',
    appId: '1:609475407163:android:54a0abb245379acf9b1b1e',
    messagingSenderId: '609475407163',
    projectId: 'gen-lang-client-0495386713',
    storageBucket: 'gen-lang-client-0495386713.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB5viG8hY2gGcDuAjdH3kZD1PyMyU0VEQ',
    appId: '1:609475407163:ios:87fba1429c415c899b1b1e',
    messagingSenderId: '609475407163',
    projectId: 'gen-lang-client-0495386713',
    storageBucket: 'gen-lang-client-0495386713.firebasestorage.app',
    iosBundleId: 'io.trasholini.vibegods.flutterClient',
  );
}
