name: flutter_client
description: "Cross-platform client for Transholini application written in Flutter."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter_svg: ^2.0.10
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:

    - assets/trashbins/bluetrashbin.svg
    - assets/trashbins/redtrashbin.svg
    - assets/trashbins/greentrashbin.svg
    - assets/trashbins/yellowtrashbin.svg
    - assets/trash_catagories/paper.jpg
    - assets/trash_catagories/plastic.jpg
    - assets/trash_catagories/organic.jpg
    - assets/trash_catagories/metal.jpg
    - assets/trash_catagories/glass.jpg
    - assets/trash_catagories/inorganic.jpg
    - assets/trash_catagories/construction.jpg
    - assets/trash_catagories/taxtile-waste.jpg
    - assets/trash_catagories/e-waste.jpg
    - assets/trash_catagories/property.jpg
    - assets/Profile/elle fanning.jpg


    
    